"""create_initial_tables

Revision ID: 220a3b2579b8
Revises: 
Create Date: 2026-09-25 19:49:04.373424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '220a3b2579b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('driver_phone', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ambulances_location', 'ambulances', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ambulances_driver_phone'), 'ambulances', ['driver_phone'], unique=True)
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('departments', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hospitals_location', 'hospitals', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('emergency_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('symptoms', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('victims', sa.Integer(), nullable=False),
    sa.Column('department_needed', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('assigned_hospital_id', sa.Integer(), nullable=True),
    sa.Column('assigned_ambulance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_ambulance_id'], ['ambulances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assigned_ambulance_id'), 'incidents', ['assigned_ambulance_id'], unique=False)
    op.create_index(op.f('ix_incidents_assigned_hospital_id'), 'incidents', ['assigned_hospital_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    op.create_table('incident_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='sent', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_broadcasts_ambulance_id'), 'incident_broadcasts', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_incident_broadcasts_id'), 'incident_broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_incident_broadcasts_incident_id'), 'incident_broadcasts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_broadcasts_status'), 'incident_broadcasts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_broadcasts_status'), table_name='incident_broadcasts')
    op.drop_index(op.f('ix_incident_broadcasts_incident_id'), table_name='incident_broadcasts')
    op.drop_index(op.f('ix_incident_broadcasts_id'), table_name='incident_broadcasts')
    op.drop_index(op.f('ix_incident_broadcasts_ambulance_id'), table_name='incident_broadcasts')
    op.drop_table('incident_broadcasts')
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_hospital_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_ambulance_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index('idx_hospitals_location', table_name='hospitals', postgresql_using='gist')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_driver_phone'), table_name='ambulances')
    op.drop_index('idx_ambulances_location', table_name='ambulances', postgresql_using='gist')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
